# Generated by Django 5.2.1 on 2025-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=100)),
                ('case_description', models.CharField(max_length=100)),
                ('case_img', models.ImageField(blank=True, null=True, upload_to='case_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('civil', 'CIVIL'), ('labour law', 'LABOUR LAW'), ('tax law', 'TAX LAW'), ('other', 'OTHER')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_experience', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('Total_cases', models.IntegerField()),
                ('Description', models.TextField()),
                ('lawyer_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
