# Generated by Django 5.2.1 on 2025-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirmmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('criminal', 'CRIMINAL'), ('divorce', 'DIVORCE'), ('consumer', 'CONSUMER'), ('civil', 'CIVIL'), ('bankruptcy', 'BANKRUPTCY'), ('environmental', 'ENVIRONMENTAL'), ('other', 'OTHER')], default='criminal', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('casedoc', models.ImageField(blank=True, null=True, upload_to='appointmentimg/')),
                ('no_of_hearings', models.IntegerField()),
                ('court_name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='casedetail',
            name='case_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='case_type',
            field=models.CharField(choices=[('criminal', 'CRIMINAL'), ('divorce', 'DIVORCE'), ('consumer', 'CONSUMER'), ('civil', 'CIVIL'), ('bankruptcy', 'BANKRUPTCY'), ('environmental', 'ENVIRONMENTAL'), ('other', 'OTHER')], default='criminal', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lawyerdetails',
            name='lawyer_img',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_img/'),
        ),
    ]
